server:
  port: 9999

application:
  unidbg:
    dynarmic: true
    verbose: false
    async: true

spring:
  application:
    name: unidbg-mt-server
  profiles:
    active: pro
  task:
    execution:
      pool:
        allow-core-thread-timeout: true
        core-size: 1
        keep-alive: 60s
        max-size: 1
